import dynamic from "next/dynamic";
import { ComponentType } from "react";

// Fallback empty page for unmapped routes
const FallbackPage = () => <div className="p-6 text-muted-foreground">Module not yet configured for tabs.</div>;

const ProcurementPurchaseRequisitionsIdPage0 = dynamic(() => import("@/app/(app)/procurement/purchase-requisitions/[id]/page"));
const ProcurementPurchaseRequisitionsNewPage1 = dynamic(() => import("@/app/(app)/procurement/purchase-requisitions/new/page"));
const ProcurementPurchaseRequisitionsPage2 = dynamic(() => import("@/app/(app)/procurement/purchase-requisitions/page"));
const ProcurementPurchaseOrdersIdPage3 = dynamic(() => import("@/app/(app)/procurement/purchase-orders/[id]/page"));
const PlanningProductionOrdersIdPage4 = dynamic(() => import("@/app/(app)/planning/production-orders/[id]/page"));
const ProcurementPurchaseOrdersNewPage5 = dynamic(() => import("@/app/(app)/procurement/purchase-orders/new/page"));
const PlanningProductionOrdersNewPage6 = dynamic(() => import("@/app/(app)/planning/production-orders/new/page"));
const ManufacturingOperationsIdPage7 = dynamic(() => import("@/app/(app)/manufacturing/operations/[id]/page"));
const MasterDataWorkCentersIdPage8 = dynamic(() => import("@/app/(app)/master-data/work-centers/[id]/page"));
const QualityInspectionPlansIdPage9 = dynamic(() => import("@/app/(app)/quality/inspection-plans/[id]/page"));
const FinanceJournalEntriesIdPage10 = dynamic(() => import("@/app/(app)/finance/journal-entries/[id]/page"));
const MaintenanceWorkOrdersIdPage11 = dynamic(() => import("@/app/(app)/maintenance/work-orders/[id]/page"));
const ManufacturingDiamondsIdPage12 = dynamic(() => import("@/app/(app)/manufacturing/diamonds/[id]/page"));
const ProcurementPurchaseOrdersPage13 = dynamic(() => import("@/app/(app)/procurement/purchase-orders/page"));
const ReturnsAuthorizationsIdPage14 = dynamic(() => import("@/app/(app)/returns/authorizations/[id]/page"));
const MaintenanceSchedulesIdPage15 = dynamic(() => import("@/app/(app)/maintenance/schedules/[id]/page"));
const ManufacturingDiamondsNewPage16 = dynamic(() => import("@/app/(app)/manufacturing/diamonds/new/page"));
const ManufacturingPacketsIdPage17 = dynamic(() => import("@/app/(app)/manufacturing/packets/[id]/page"));
const MasterDataCustomersIdPage18 = dynamic(() => import("@/app/(app)/master-data/customers/[id]/page"));
const PlanningProductionOrdersPage19 = dynamic(() => import("@/app/(app)/planning/production-orders/page"));
const ReturnsRepairOrdersIdPage20 = dynamic(() => import("@/app/(app)/returns/repair-orders/[id]/page"));
const FinanceChartOfAccountsPage21 = dynamic(() => import("@/app/(app)/finance/chart-of-accounts/page"));
const ManufacturingPacketsNewPage22 = dynamic(() => import("@/app/(app)/manufacturing/packets/new/page"));
const MasterDataProductsIdPage23 = dynamic(() => import("@/app/(app)/master-data/products/[id]/page"));
const QualityCertificatesIdPage24 = dynamic(() => import("@/app/(app)/quality/certificates/[id]/page"));
const InventoryPhysicalCountPage25 = dynamic(() => import("@/app/(app)/inventory/physical-count/page"));
const ManufacturingOperationsPage26 = dynamic(() => import("@/app/(app)/manufacturing/operations/page"));
const ManufacturingShopFloorPage27 = dynamic(() => import("@/app/(app)/manufacturing/shop-floor/page"));
const MasterDataVendorsIdPage28 = dynamic(() => import("@/app/(app)/master-data/vendors/[id]/page"));
const MasterDataWorkCentersPage29 = dynamic(() => import("@/app/(app)/master-data/work-centers/page"));
const ProcurementRequisitionsPage30 = dynamic(() => import("@/app/(app)/procurement/requisitions/page"));
const QualityInspectionPlansPage31 = dynamic(() => import("@/app/(app)/quality/inspection-plans/page"));
const QualityInspectionsIdPage32 = dynamic(() => import("@/app/(app)/quality/inspections/[id]/page"));
const DispatchShipmentsIdPage33 = dynamic(() => import("@/app/(app)/dispatch/shipments/[id]/page"));
const FinanceJournalEntriesPage34 = dynamic(() => import("@/app/(app)/finance/journal-entries/page"));
const MaintenanceAssetsIdPage35 = dynamic(() => import("@/app/(app)/maintenance/assets/[id]/page"));
const MaintenanceWorkOrdersPage36 = dynamic(() => import("@/app/(app)/maintenance/work-orders/page"));
const ManufacturingJobCardsPage37 = dynamic(() => import("@/app/(app)/manufacturing/job-cards/page"));
const MasterDataVendorsNewPage38 = dynamic(() => import("@/app/(app)/master-data/vendors/new/page"));
const DispatchCarriersIdPage39 = dynamic(() => import("@/app/(app)/dispatch/carriers/[id]/page"));
const InventoryTransactionsPage40 = dynamic(() => import("@/app/(app)/inventory/transactions/page"));
const ManufacturingDiamondsPage41 = dynamic(() => import("@/app/(app)/manufacturing/diamonds/page"));
const ReturnsAuthorizationsPage42 = dynamic(() => import("@/app/(app)/returns/authorizations/page"));
const DispatchBaggingIdPage43 = dynamic(() => import("@/app/(app)/dispatch/bagging/[id]/page"));
const FinanceInvoicesIdPage44 = dynamic(() => import("@/app/(app)/finance/invoices/[id]/page"));
const FinancePaymentsIdPage45 = dynamic(() => import("@/app/(app)/finance/payments/[id]/page"));
const InventoryAdjustmentsPage46 = dynamic(() => import("@/app/(app)/inventory/adjustments/page"));
const MaintenanceSchedulesPage47 = dynamic(() => import("@/app/(app)/maintenance/schedules/page"));
const ManufacturingPacketsPage48 = dynamic(() => import("@/app/(app)/manufacturing/packets/page"));
const MasterDataCustomersPage49 = dynamic(() => import("@/app/(app)/master-data/customers/page"));
const ReturnsRepairOrdersPage50 = dynamic(() => import("@/app/(app)/returns/repair-orders/page"));
const SalesQuotationsIdPage51 = dynamic(() => import("@/app/(app)/sales/quotations/[id]/page"));
const MasterDataProductsPage52 = dynamic(() => import("@/app/(app)/master-data/products/page"));
const QualityCertificatesPage53 = dynamic(() => import("@/app/(app)/quality/certificates/page"));
const SalesQuotationsNewPage54 = dynamic(() => import("@/app/(app)/sales/quotations/new/page"));
const AdminFeatureFlagsPage55 = dynamic(() => import("@/app/(app)/admin/feature-flags/page"));
const AnalyticsWipAgingPage56 = dynamic(() => import("@/app/(app)/analytics/wip-aging/page"));
const InventoryLotsIdPage57 = dynamic(() => import("@/app/(app)/inventory/lots/[id]/page"));
const InventoryTransfersPage58 = dynamic(() => import("@/app/(app)/inventory/transfers/page"));
const MasterDataVendorsPage59 = dynamic(() => import("@/app/(app)/master-data/vendors/page"));
const QualityInspectionsPage60 = dynamic(() => import("@/app/(app)/quality/inspections/page"));
const AiToolsIdEditPage61 = dynamic(() => import("@/app/(app)/ai/tools/[id]/edit/page"));
const AnalyticsCapacityPage62 = dynamic(() => import("@/app/(app)/analytics/capacity/page"));
const DispatchShipmentsPage63 = dynamic(() => import("@/app/(app)/dispatch/shipments/page"));
const InventoryErpSyncPage64 = dynamic(() => import("@/app/(app)/inventory/erp-sync/page"));
const InventoryLotsNewPage65 = dynamic(() => import("@/app/(app)/inventory/lots/new/page"));
const MaintenanceAssetsPage66 = dynamic(() => import("@/app/(app)/maintenance/assets/page"));
const AdminPermissionsPage67 = dynamic(() => import("@/app/(app)/admin/permissions/page"));
const DispatchCarriersPage68 = dynamic(() => import("@/app/(app)/dispatch/carriers/page"));
const ManufacturingWipPage69 = dynamic(() => import("@/app/(app)/manufacturing/wip/page"));
const PlanningCapacityPage70 = dynamic(() => import("@/app/(app)/planning/capacity/page"));
const QualityNcrsIdPage71 = dynamic(() => import("@/app/(app)/quality/ncrs/[id]/page"));
const SalesOrdersIdPage72 = dynamic(() => import("@/app/(app)/sales/orders/[id]/page"));
const AnalyticsCustomPage73 = dynamic(() => import("@/app/(app)/analytics/custom/page"));
const DispatchBaggingPage74 = dynamic(() => import("@/app/(app)/dispatch/bagging/page"));
const FinanceInvoicesPage75 = dynamic(() => import("@/app/(app)/finance/invoices/page"));
const FinancePaymentsPage76 = dynamic(() => import("@/app/(app)/finance/payments/page"));
const ProcurementRfqsPage77 = dynamic(() => import("@/app/(app)/procurement/rfqs/page"));
const ReturnsReceiptsPage78 = dynamic(() => import("@/app/(app)/returns/receipts/page"));
const SalesOrdersNewPage79 = dynamic(() => import("@/app/(app)/sales/orders/new/page"));
const SalesQuotationsPage80 = dynamic(() => import("@/app/(app)/sales/quotations/page"));
const AdminAuditLogPage81 = dynamic(() => import("@/app/(app)/admin/audit-log/page"));
const AnalyticsYieldPage82 = dynamic(() => import("@/app/(app)/analytics/yield/page"));
const InventoryLotsPage83 = dynamic(() => import("@/app/(app)/inventory/lots/page"));
const AiToolsIdPage84 = dynamic(() => import("@/app/(app)/ai/tools/[id]/page"));
const AnalyticsOeePage85 = dynamic(() => import("@/app/(app)/analytics/oee/page"));
const AnalyticsOtdPage86 = dynamic(() => import("@/app/(app)/analytics/otd/page"));
const AiAuditLogPage87 = dynamic(() => import("@/app/(app)/ai/audit-log/page"));
const AiToolsNewPage88 = dynamic(() => import("@/app/(app)/ai/tools/new/page"));
const PlanningMrpPage89 = dynamic(() => import("@/app/(app)/planning/mrp/page"));
const QualityNcrsPage90 = dynamic(() => import("@/app/(app)/quality/ncrs/page"));
const SalesOrdersPage91 = dynamic(() => import("@/app/(app)/sales/orders/page"));
const AdminRolesPage92 = dynamic(() => import("@/app/(app)/admin/roles/page"));
const AdminUsersPage93 = dynamic(() => import("@/app/(app)/admin/users/page"));
const AnalyticsPage94 = dynamic(() => import("@/app/(app)/analytics/page"));
const DashboardPage95 = dynamic(() => import("@/app/(app)/dashboard/page"));
const AiToolsPage96 = dynamic(() => import("@/app/(app)/ai/tools/page"));
const AiChatPage97 = dynamic(() => import("@/app/(app)/ai/chat/page"));
const ProfilePage98 = dynamic(() => import("@/app/(app)/profile/page"));

export function getComponentForUrl(url: string): ComponentType<any> {
  if (new RegExp('^' + '\\/procurement\\/purchase-requisitions\\/[^\\/]+' + '$').test(url)) return ProcurementPurchaseRequisitionsIdPage0;
  if (url === "/procurement/purchase-requisitions/new") return ProcurementPurchaseRequisitionsNewPage1;
  if (url === "/procurement/purchase-requisitions") return ProcurementPurchaseRequisitionsPage2;
  if (new RegExp('^' + '\\/procurement\\/purchase-orders\\/[^\\/]+' + '$').test(url)) return ProcurementPurchaseOrdersIdPage3;
  if (new RegExp('^' + '\\/planning\\/production-orders\\/[^\\/]+' + '$').test(url)) return PlanningProductionOrdersIdPage4;
  if (url === "/procurement/purchase-orders/new") return ProcurementPurchaseOrdersNewPage5;
  if (url === "/planning/production-orders/new") return PlanningProductionOrdersNewPage6;
  if (new RegExp('^' + '\\/manufacturing\\/operations\\/[^\\/]+' + '$').test(url)) return ManufacturingOperationsIdPage7;
  if (new RegExp('^' + '\\/master-data\\/work-centers\\/[^\\/]+' + '$').test(url)) return MasterDataWorkCentersIdPage8;
  if (new RegExp('^' + '\\/quality\\/inspection-plans\\/[^\\/]+' + '$').test(url)) return QualityInspectionPlansIdPage9;
  if (new RegExp('^' + '\\/finance\\/journal-entries\\/[^\\/]+' + '$').test(url)) return FinanceJournalEntriesIdPage10;
  if (new RegExp('^' + '\\/maintenance\\/work-orders\\/[^\\/]+' + '$').test(url)) return MaintenanceWorkOrdersIdPage11;
  if (new RegExp('^' + '\\/manufacturing\\/diamonds\\/[^\\/]+' + '$').test(url)) return ManufacturingDiamondsIdPage12;
  if (url === "/procurement/purchase-orders") return ProcurementPurchaseOrdersPage13;
  if (new RegExp('^' + '\\/returns\\/authorizations\\/[^\\/]+' + '$').test(url)) return ReturnsAuthorizationsIdPage14;
  if (new RegExp('^' + '\\/maintenance\\/schedules\\/[^\\/]+' + '$').test(url)) return MaintenanceSchedulesIdPage15;
  if (url === "/manufacturing/diamonds/new") return ManufacturingDiamondsNewPage16;
  if (new RegExp('^' + '\\/manufacturing\\/packets\\/[^\\/]+' + '$').test(url)) return ManufacturingPacketsIdPage17;
  if (new RegExp('^' + '\\/master-data\\/customers\\/[^\\/]+' + '$').test(url)) return MasterDataCustomersIdPage18;
  if (url === "/planning/production-orders") return PlanningProductionOrdersPage19;
  if (new RegExp('^' + '\\/returns\\/repair-orders\\/[^\\/]+' + '$').test(url)) return ReturnsRepairOrdersIdPage20;
  if (url === "/finance/chart-of-accounts") return FinanceChartOfAccountsPage21;
  if (url === "/manufacturing/packets/new") return ManufacturingPacketsNewPage22;
  if (new RegExp('^' + '\\/master-data\\/products\\/[^\\/]+' + '$').test(url)) return MasterDataProductsIdPage23;
  if (new RegExp('^' + '\\/quality\\/certificates\\/[^\\/]+' + '$').test(url)) return QualityCertificatesIdPage24;
  if (url === "/inventory/physical-count") return InventoryPhysicalCountPage25;
  if (url === "/manufacturing/operations") return ManufacturingOperationsPage26;
  if (url === "/manufacturing/shop-floor") return ManufacturingShopFloorPage27;
  if (new RegExp('^' + '\\/master-data\\/vendors\\/[^\\/]+' + '$').test(url)) return MasterDataVendorsIdPage28;
  if (url === "/master-data/work-centers") return MasterDataWorkCentersPage29;
  if (url === "/procurement/requisitions") return ProcurementRequisitionsPage30;
  if (url === "/quality/inspection-plans") return QualityInspectionPlansPage31;
  if (new RegExp('^' + '\\/quality\\/inspections\\/[^\\/]+' + '$').test(url)) return QualityInspectionsIdPage32;
  if (new RegExp('^' + '\\/dispatch\\/shipments\\/[^\\/]+' + '$').test(url)) return DispatchShipmentsIdPage33;
  if (url === "/finance/journal-entries") return FinanceJournalEntriesPage34;
  if (new RegExp('^' + '\\/maintenance\\/assets\\/[^\\/]+' + '$').test(url)) return MaintenanceAssetsIdPage35;
  if (url === "/maintenance/work-orders") return MaintenanceWorkOrdersPage36;
  if (url === "/manufacturing/job-cards") return ManufacturingJobCardsPage37;
  if (url === "/master-data/vendors/new") return MasterDataVendorsNewPage38;
  if (new RegExp('^' + '\\/dispatch\\/carriers\\/[^\\/]+' + '$').test(url)) return DispatchCarriersIdPage39;
  if (url === "/inventory/transactions") return InventoryTransactionsPage40;
  if (url === "/manufacturing/diamonds") return ManufacturingDiamondsPage41;
  if (url === "/returns/authorizations") return ReturnsAuthorizationsPage42;
  if (new RegExp('^' + '\\/dispatch\\/bagging\\/[^\\/]+' + '$').test(url)) return DispatchBaggingIdPage43;
  if (new RegExp('^' + '\\/finance\\/invoices\\/[^\\/]+' + '$').test(url)) return FinanceInvoicesIdPage44;
  if (new RegExp('^' + '\\/finance\\/payments\\/[^\\/]+' + '$').test(url)) return FinancePaymentsIdPage45;
  if (url === "/inventory/adjustments") return InventoryAdjustmentsPage46;
  if (url === "/maintenance/schedules") return MaintenanceSchedulesPage47;
  if (url === "/manufacturing/packets") return ManufacturingPacketsPage48;
  if (url === "/master-data/customers") return MasterDataCustomersPage49;
  if (url === "/returns/repair-orders") return ReturnsRepairOrdersPage50;
  if (new RegExp('^' + '\\/sales\\/quotations\\/[^\\/]+' + '$').test(url)) return SalesQuotationsIdPage51;
  if (url === "/master-data/products") return MasterDataProductsPage52;
  if (url === "/quality/certificates") return QualityCertificatesPage53;
  if (url === "/sales/quotations/new") return SalesQuotationsNewPage54;
  if (url === "/admin/feature-flags") return AdminFeatureFlagsPage55;
  if (url === "/analytics/wip-aging") return AnalyticsWipAgingPage56;
  if (new RegExp('^' + '\\/inventory\\/lots\\/[^\\/]+' + '$').test(url)) return InventoryLotsIdPage57;
  if (url === "/inventory/transfers") return InventoryTransfersPage58;
  if (url === "/master-data/vendors") return MasterDataVendorsPage59;
  if (url === "/quality/inspections") return QualityInspectionsPage60;
  if (new RegExp('^' + '\\/ai\\/tools\\/[^\\/]+\\/edit' + '$').test(url)) return AiToolsIdEditPage61;
  if (url === "/analytics/capacity") return AnalyticsCapacityPage62;
  if (url === "/dispatch/shipments") return DispatchShipmentsPage63;
  if (url === "/inventory/erp-sync") return InventoryErpSyncPage64;
  if (url === "/inventory/lots/new") return InventoryLotsNewPage65;
  if (url === "/maintenance/assets") return MaintenanceAssetsPage66;
  if (url === "/admin/permissions") return AdminPermissionsPage67;
  if (url === "/dispatch/carriers") return DispatchCarriersPage68;
  if (url === "/manufacturing/wip") return ManufacturingWipPage69;
  if (url === "/planning/capacity") return PlanningCapacityPage70;
  if (new RegExp('^' + '\\/quality\\/ncrs\\/[^\\/]+' + '$').test(url)) return QualityNcrsIdPage71;
  if (new RegExp('^' + '\\/sales\\/orders\\/[^\\/]+' + '$').test(url)) return SalesOrdersIdPage72;
  if (url === "/analytics/custom") return AnalyticsCustomPage73;
  if (url === "/dispatch/bagging") return DispatchBaggingPage74;
  if (url === "/finance/invoices") return FinanceInvoicesPage75;
  if (url === "/finance/payments") return FinancePaymentsPage76;
  if (url === "/procurement/rfqs") return ProcurementRfqsPage77;
  if (url === "/returns/receipts") return ReturnsReceiptsPage78;
  if (url === "/sales/orders/new") return SalesOrdersNewPage79;
  if (url === "/sales/quotations") return SalesQuotationsPage80;
  if (url === "/admin/audit-log") return AdminAuditLogPage81;
  if (url === "/analytics/yield") return AnalyticsYieldPage82;
  if (url === "/inventory/lots") return InventoryLotsPage83;
  if (new RegExp('^' + '\\/ai\\/tools\\/[^\\/]+' + '$').test(url)) return AiToolsIdPage84;
  if (url === "/analytics/oee") return AnalyticsOeePage85;
  if (url === "/analytics/otd") return AnalyticsOtdPage86;
  if (url === "/ai/audit-log") return AiAuditLogPage87;
  if (url === "/ai/tools/new") return AiToolsNewPage88;
  if (url === "/planning/mrp") return PlanningMrpPage89;
  if (url === "/quality/ncrs") return QualityNcrsPage90;
  if (url === "/sales/orders") return SalesOrdersPage91;
  if (url === "/admin/roles") return AdminRolesPage92;
  if (url === "/admin/users") return AdminUsersPage93;
  if (url === "/analytics") return AnalyticsPage94;
  if (url === "/dashboard") return DashboardPage95;
  if (url === "/ai/tools") return AiToolsPage96;
  if (url === "/ai/chat") return AiChatPage97;
  if (url === "/profile") return ProfilePage98;
  return FallbackPage;
}
